### PR TITLE
feat(TeamsPage): created pages for teams

### LINKED ISSUE #23: Sprint 1: Team Page
**Sprint 1**: create a general page for teams
Populate "your pages" screen with the pages the user is a part of as a button (look at prototype)
have the buttons be navigated to the general teams page you created
generate the team page based on the team they chose (pass the team as a prop)

### PR DESCRIPTION
**Pull request by Tonewall**
#23 
Created teams page and passed the states to all of the pages
Each page should know user's info and which committee/team they chose

### CODE REVIEW

**Review by ivelmiskin3 — APPROVED** [review]
The functionality is there - the Committee Page title text looks weird though especially for the longer committees

**Comment by Tonewall** [comment]
> The functionality is there - the Committee Page title text looks weird though especially for the longer committees

Try it now

**Comment by ivelmiskin3** [comment]
I think the issue is when the text wraps it left-aligns which gives the title a weird look. It might also be a screen dimension issue

**Comment by Tonewall** [comment]
> I think the issue is when the text wraps it left-aligns which gives the title a weird look. It might also be a screen dimension issue

Fixed it

**Comment by ivelmiskin3** [comment]
Titles look good, user [a@e.com, pass: lastName] has their Committee button bleed into the Executive button 
Additionally, may as well move users to their only page if they're only part of one committee

**Comment by Tonewall** [comment]
> Titles look good, user [[a@e.com](mailto:a@e.com), pass: lastName] has their Committee button bleed into the Executive button
> Additionally, may as well move users to their only page if they're only part of one committee

Good idea and good catch. Just made the changes so it should direct user directly to their committee page if they're not in exec. Also fixed the button layout.

**Comment by Tonewall** [comment]
Screw it, I'm just going to merge it since no one else will look at it

**Pull request merged**
